apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: hello-node
build:
  artifacts:
  - image: ananthrs/hello-node
    context: .
  local:
    push: false
  tagPolicy:
    envTemplate:
      template: "latest"
deploy:
  helm:
    releases:
    - name: hello-node-release
      chartPath: helm/hello-node
      setValueTemplates:
        image.tag: "latest"
