/*
 * Product Registration
 * An API spec for product registration flows 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * OpenAPI generator version: 5.1.0-SNAPSHOT
 */


import http from "k6/http";
import { group, check, sleep } from "k6";

const BASE_URL = "https://virtserver.swaggerhub.com/ananthr/product/1.0.0";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function() {
    group("/beta/register", () => {
        let url = BASE_URL + `/beta/register`;
        // Request No. 1
        // TODO: edit the parameters of the request body.
        let body = {"firstName": "string", "lastName": "string", "email": "string", "twitter": "string", "instagram": "string", "location": "string", "devEnvironment": "string"};
        let params = {headers: {"Content-Type": "application/json", "Accept": "application/json"}};
        let request = http.post(url, body, params);
        check(request, {
            "registeration successful": (r) => r.status === 200
        });
        sleep(SLEEP_DURATION);
    });
    group("/beta/getUserList", () => {
        let offset = "TODO_EDIT_THE_OFFSET";
        let limit = "TODO_EDIT_THE_LIMIT";
        let url = BASE_URL + `/beta/getUserList?offset=${offset}&limit=${limit}`;
        // Request No. 1
        let request = http.get(url);
        check(request, {
            "success": (r) => r.status === 200
        });
        sleep(SLEEP_DURATION);
    });
    group("/healthz", () => {
        let url = BASE_URL + `/healthz`;
        // Request No. 1
        let request = http.get(url);
        check(request, {
            "Healthy": (r) => r.status === 200
        });
        sleep(SLEEP_DURATION);
    });
}
